/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import PatronesDiseño.EmpresaVisitador;

/**
 *
 * @author Daniela Chaux
 */
public class PnlEmpresaPrincipal extends javax.swing.JPanel {

    /**
     * Creates new form PnlEmpresaPrincipal
     */
    public PnlEmpresaPrincipal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jPanel = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BtnCrearProyecto = new javax.swing.JButton();
        BtnVerProyecto = new javax.swing.JButton();
        BtnRegistro = new javax.swing.JButton();
        BtnSalir = new javax.swing.JButton();

        jPanel.setLayout(new java.awt.BorderLayout());

        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 5, 0, 5, 0};
        jPanel2Layout.rowHeights = new int[] {0, 8, 0, 8, 0};
        jPanel2.setLayout(jPanel2Layout);

        BtnCrearProyecto.setText("Crear Proyecto");
        BtnCrearProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCrearProyectoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        jPanel2.add(BtnCrearProyecto, gridBagConstraints);

        BtnVerProyecto.setText("Ver Proyectos");
        BtnVerProyecto.setPreferredSize(new java.awt.Dimension(105, 23));
        BtnVerProyecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnVerProyectoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        jPanel2.add(BtnVerProyecto, gridBagConstraints);

        BtnRegistro.setText("Registro");
        BtnRegistro.setPreferredSize(new java.awt.Dimension(105, 23));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        jPanel2.add(BtnRegistro, gridBagConstraints);

        BtnSalir.setText("Salir");
        BtnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnSalirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.ipadx = 54;
        gridBagConstraints.insets = new java.awt.Insets(0, 6, 0, 6);
        jPanel2.add(BtnSalir, gridBagConstraints);

        jPanel.add(jPanel2, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 310, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 286, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(12, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void BtnCrearProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCrearProyectoActionPerformed
        // TODO add your handling code here:
        visitador.cambiarTarjeta("CrearProyecto");
    }//GEN-LAST:event_BtnCrearProyectoActionPerformed

    private void BtnVerProyectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnVerProyectoActionPerformed
        // TODO add your handling code here:
        visitador.cargarLista();
        visitador.cambiarTarjeta("Proyecto");
    }//GEN-LAST:event_BtnVerProyectoActionPerformed

    private void BtnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnSalirActionPerformed
        // TODO add your handling code here:
        visitador.cambiarTarjetaAbuelo("Inicio");
    }//GEN-LAST:event_BtnSalirActionPerformed

    public void setVisitador(EmpresaVisitador visitador) {
        this.visitador = visitador;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCrearProyecto;
    private javax.swing.JButton BtnRegistro;
    private javax.swing.JButton BtnSalir;
    private javax.swing.JButton BtnVerProyecto;
    private javax.swing.JPanel jPanel;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
    private EmpresaVisitador visitador;
}
