/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import PatronesDiseño.EmpresaVisitador;
import PatronesDiseño.PrincipalVisitador;
import java.awt.CardLayout;
import javax.swing.JList;

/**
 *
 * @author Daniela Chaux
 */
public class PnlEmpresa extends javax.swing.JPanel implements EmpresaVisitador{

    /**
     * Creates new form PnlEmpresa
     */
    public PnlEmpresa() {
        initComponents();
        pnlEmpresaPrincipal1.setVisitador(this);
        pnlProyecto1.setVisitador(this);
        pnlCrearProyecto1.setVisitador(this);
    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        PnlCartas = new javax.swing.JPanel();
        pnlEmpresaPrincipal1 = new Vista.PnlEmpresaPrincipal();
        pnlCrearProyecto1 = new Vista.PnlCrearProyecto();
        pnlProyecto1 = new Vista.PnlProyecto();

        jPanel.setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Usuario Adiminastrador");
        jPanel.add(jLabel1, java.awt.BorderLayout.PAGE_START);

        PnlCartas.setLayout(new java.awt.CardLayout());
        PnlCartas.add(pnlEmpresaPrincipal1, "Principal");
        PnlCartas.add(pnlCrearProyecto1, "CrearProyecto");
        PnlCartas.add(pnlProyecto1, "Proyecto");

        jPanel.add(PnlCartas, java.awt.BorderLayout.CENTER);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.DEFAULT_SIZE, 420, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 315, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    public void setVisitador(PrincipalVisitador visitador) {
        this.visitador = visitador;
    }
    public void cambiarTarjeta(String tarjeta) {
         ((CardLayout) PnlCartas.getLayout()).show(PnlCartas, tarjeta);
    }
    public void cambiarTarjetaAbuelo(String tarjeta){
        visitador.cambiarTarjeta("Inicio");
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel PnlCartas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel;
    private Vista.PnlCrearProyecto pnlCrearProyecto1;
    private Vista.PnlEmpresaPrincipal pnlEmpresaPrincipal1;
    private Vista.PnlProyecto pnlProyecto1;
    // End of variables declaration//GEN-END:variables
    private PrincipalVisitador visitador;
}



