/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.EmpresaControlador;
import PatronesDiseño.TrabajadorVisitador;
import javax.swing.JOptionPane;

/**
 *
 * @author Daniela Chaux
 */
public class PnlInicioTrabajador extends javax.swing.JPanel {

    /**
     * Creates new form PnlInicioTrabajador
     */
    public PnlInicioTrabajador() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        TxtUsuairo = new javax.swing.JTextField();
        BtnIngresar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        btnSalir = new javax.swing.JButton();

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 8, 0, 8, 0};
        layout.rowHeights = new int[] {0, 8, 0, 8, 0};
        setLayout(layout);

        jLabel1.setText("Usuario:");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        add(jLabel1, gridBagConstraints);

        TxtUsuairo.setPreferredSize(new java.awt.Dimension(70, 30));
        TxtUsuairo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtUsuairoActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 2;
        add(TxtUsuairo, gridBagConstraints);

        BtnIngresar.setText("Ingresar");
        BtnIngresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnIngresarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        add(BtnIngresar, gridBagConstraints);

        jLabel2.setText("Inicio Sesion");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 0;
        add(jLabel2, gridBagConstraints);

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        add(btnSalir, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void TxtUsuairoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtUsuairoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtUsuairoActionPerformed

    private void BtnIngresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnIngresarActionPerformed
       
        if(visitador.inicioSesion(Long.parseLong(TxtUsuairo.getText()))){
           visitador.cambiarTarjeta("Trabajador");
       }
       else{
           JOptionPane.showMessageDialog(null, "Ingrese un usuario correcto");
       }
    }//GEN-LAST:event_BtnIngresarActionPerformed

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        // TODO add your handling code here:
       visitador.cambiarTarjetaAbuelo("Inicio");
    }//GEN-LAST:event_btnSalirActionPerformed

    public void setVisitador(TrabajadorVisitador visitador) {
        this.visitador = visitador;
    }
    
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnIngresar;
    private javax.swing.JTextField TxtUsuairo;
    private javax.swing.JButton btnSalir;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    // End of variables declaration//GEN-END:variables
    private TrabajadorVisitador visitador;
}
