package Vista;

import PatronesDiseño.PrincipalVisitador;
import java.security.Principal;

/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

/**
 *
 * @author Daniela Chaux
 */
public class PnlInicio extends javax.swing.JPanel {

    /**
     * Creates new form PnlInicio
     */
    public PnlInicio() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jLabel1 = new javax.swing.JLabel();
        BtnAdministrador = new javax.swing.JButton();
        BtnTrabajador = new javax.swing.JButton();

        java.awt.GridBagLayout layout = new java.awt.GridBagLayout();
        layout.columnWidths = new int[] {0, 8, 0, 8, 0, 8, 0, 8, 0};
        layout.rowHeights = new int[] {0, 8, 0, 8, 0};
        setLayout(layout);

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jLabel1.setText("Acceso");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 4;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.ipadx = 18;
        gridBagConstraints.insets = new java.awt.Insets(0, 23, 0, 23);
        add(jLabel1, gridBagConstraints);

        BtnAdministrador.setText("Administrador");
        BtnAdministrador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnAdministradorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 4;
        add(BtnAdministrador, gridBagConstraints);

        BtnTrabajador.setText("Trabajador");
        BtnTrabajador.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTrabajadorActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 4;
        add(BtnTrabajador, gridBagConstraints);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnAdministradorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnAdministradorActionPerformed
        // TODO add your handling code here:
        visitador.cambiarTarjeta("Proyecto");
    }//GEN-LAST:event_BtnAdministradorActionPerformed

    private void BtnTrabajadorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTrabajadorActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnTrabajadorActionPerformed

    public void setVisitador(PrincipalVisitador visitador) {
        this.visitador = visitador;
    }

    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnAdministrador;
    private javax.swing.JButton BtnTrabajador;
    private javax.swing.JLabel jLabel1;
    // End of variables declaration//GEN-END:variables
    private PrincipalVisitador visitador;
}

