/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import PatronesDiseño.EmpresaVisitador;
import PatronesDiseño.ProyectoVisitador;
import java.awt.CardLayout;
import javax.swing.DefaultListModel;


/**
 *
 * @author Daniela Chaux
 */
public class PnlProyecto extends javax.swing.JPanel implements ProyectoVisitador{

    /**
     * Creates new form PnlProyecto
     */
    public PnlProyecto() {
        initComponents();
        pnlProyectoAgregarT1.setVisitador(this);
        pnlProyectoAgregarU1.setVisitador(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        jToggleButton1 = new javax.swing.JToggleButton();
        jToggleButton2 = new javax.swing.JToggleButton();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jSplitPane1 = new javax.swing.JSplitPane();
        pnlTarjetas = new javax.swing.JPanel();
        pnlProyectoAgregarT1 = new Vista.PnlProyectoAgregarT();
        pnlProyectoAgregarU1 = new Vista.PnlProyectoAgregarU();
        PnlListaProyectos = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        BtnUsuario = new javax.swing.JButton();
        BtnRegistro = new javax.swing.JButton();
        BtnTarea = new javax.swing.JButton();
        BtnCancelar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jList1 = new javax.swing.JList();

        jToggleButton1.setText("jToggleButton1");

        jToggleButton2.setText("jToggleButton2");

        setLayout(new java.awt.BorderLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("PROYECTOS");
        add(jLabel1, java.awt.BorderLayout.PAGE_START);

        pnlTarjetas.setPreferredSize(new java.awt.Dimension(25, 254));
        pnlTarjetas.setLayout(new java.awt.CardLayout());
        pnlTarjetas.add(pnlProyectoAgregarT1, "Tarea");
        pnlTarjetas.add(pnlProyectoAgregarU1, "Usuario");

        jSplitPane1.setRightComponent(pnlTarjetas);

        PnlListaProyectos.setLayout(new java.awt.BorderLayout());

        java.awt.GridBagLayout jPanel2Layout = new java.awt.GridBagLayout();
        jPanel2Layout.columnWidths = new int[] {0, 5, 0};
        jPanel2Layout.rowHeights = new int[] {0, 8, 0, 8, 0, 8, 0, 8, 0, 8, 0};
        jPanel2.setLayout(jPanel2Layout);

        BtnUsuario.setText("Usuario");
        BtnUsuario.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnUsuarioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(9, 0, 9, 0);
        jPanel2.add(BtnUsuario, gridBagConstraints);

        BtnRegistro.setText("Registro");
        BtnRegistro.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnRegistroActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(9, 0, 9, 0);
        jPanel2.add(BtnRegistro, gridBagConstraints);

        BtnTarea.setText("Tarea");
        BtnTarea.setPreferredSize(new java.awt.Dimension(73, 23));
        BtnTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnTareaActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.fill = java.awt.GridBagConstraints.HORIZONTAL;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(9, 0, 9, 0);
        jPanel2.add(BtnTarea, gridBagConstraints);

        BtnCancelar.setText("Cancelar");
        BtnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BtnCancelarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.ipadx = 2;
        gridBagConstraints.ipady = 3;
        gridBagConstraints.insets = new java.awt.Insets(9, 0, 0, 0);
        jPanel2.add(BtnCancelar, gridBagConstraints);

        PnlListaProyectos.add(jPanel2, java.awt.BorderLayout.PAGE_END);

        jList1.setModel(new javax.swing.AbstractListModel() {
            String[] strings = { " " };
            public int getSize() { return strings.length; }
            public Object getElementAt(int i) { return strings[i]; }
        });
        jScrollPane1.setViewportView(jList1);

        PnlListaProyectos.add(jScrollPane1, java.awt.BorderLayout.CENTER);

        jSplitPane1.setLeftComponent(PnlListaProyectos);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );

        add(jPanel1, java.awt.BorderLayout.CENTER);
    }// </editor-fold>//GEN-END:initComponents

    private void BtnRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_BtnRegistroActionPerformed

    private void BtnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnCancelarActionPerformed
        // TODO add your handling code here:
        visitador.cambiarTarjeta("Principal");
    }//GEN-LAST:event_BtnCancelarActionPerformed

    private void BtnUsuarioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnUsuarioActionPerformed
        // TODO add your handling code here:
        cambiarTarjeta("Usuario");
    }//GEN-LAST:event_BtnUsuarioActionPerformed

    private void BtnTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BtnTareaActionPerformed
        // TODO add your handling code here:
        cambiarTarjeta("Tarea");
    }//GEN-LAST:event_BtnTareaActionPerformed
    public void setVisitador(EmpresaVisitador visitador) {
        this.visitador = visitador;
    }
    
    public void cambiarTarjeta(String tarjeta){
        ((CardLayout) pnlTarjetas.getLayout()).show(pnlTarjetas, tarjeta);
        if(tarjeta.equals("Tarea"))
            pnlProyectoAgregarT1.vaciarCampos();
        else if(tarjeta.equals("Usuario"))
            pnlProyectoAgregarU1.vaciarCampos();
    }
    void cargarLista(){
        modeloLista = new DefaultListModel();
        jList1.setModel(modeloLista);
        
        
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BtnCancelar;
    private javax.swing.JButton BtnRegistro;
    private javax.swing.JButton BtnTarea;
    private javax.swing.JButton BtnUsuario;
    private javax.swing.JPanel PnlListaProyectos;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JList jList1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JToggleButton jToggleButton1;
    private javax.swing.JToggleButton jToggleButton2;
    private Vista.PnlProyectoAgregarT pnlProyectoAgregarT1;
    private Vista.PnlProyectoAgregarU pnlProyectoAgregarU1;
    private javax.swing.JPanel pnlTarjetas;
    // End of variables declaration//GEN-END:variables
    private EmpresaVisitador visitador;
    private DefaultListModel modeloLista;
}
