/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

import Controlador.EmpresaControlador;
import Modelo.*;
import PatronesDiseño.TrabajadorVisitador;
import java.awt.CardLayout;
import java.util.List;
import javax.swing.DefaultListModel;
import org.joda.time.DateTime;
import org.joda.time.Minutes;

/**
 *
 * @author Daniela Chaux
 */
public class Trabajador extends javax.swing.JPanel {
    /**
     * Creates new form Trabajador
     */
    public Trabajador() {
        initComponents();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnGrEstado = new javax.swing.ButtonGroup();
        jSplitPane1 = new javax.swing.JSplitPane();
        jScrollPane1 = new javax.swing.JScrollPane();
        listProyectos = new javax.swing.JList();
        pnlCartas = new javax.swing.JPanel();
        pnlInfoUsuario = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtId = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        listTareas = new javax.swing.JList();
        jLabel4 = new javax.swing.JLabel();
        btnRegistro = new javax.swing.JButton();
        btnVer = new javax.swing.JButton();
        btnSalir = new javax.swing.JButton();
        pnlTarea = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        txtTarea = new javax.swing.JLabel();
        txtDescripcion = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtEstado = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        btnParar = new javax.swing.JButton();
        btnSuspender = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        txtRealizadoTarea = new javax.swing.JTextField();
        rbtnPendiente = new javax.swing.JRadioButton();
        rbtnFinalizado = new javax.swing.JRadioButton();
        pnlSuspender = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        txtDescripcionSuspension = new javax.swing.JTextField();
        btnFinalizarSuspension = new javax.swing.JButton();

        listProyectos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseReleased(java.awt.event.MouseEvent evt) {
                listProyectosMouseReleased(evt);
            }
        });
        jScrollPane1.setViewportView(listProyectos);

        jSplitPane1.setLeftComponent(jScrollPane1);

        pnlCartas.setLayout(new java.awt.CardLayout());

        jLabel1.setText("Nombre:");

        jLabel2.setText("Identificacion");

        jScrollPane2.setViewportView(listTareas);

        jLabel4.setText("Tareas:");

        btnRegistro.setText("Registro");

        btnVer.setText("Ver");
        btnVer.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVerActionPerformed(evt);
            }
        });

        btnSalir.setText("Salir");
        btnSalir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSalirActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnlInfoUsuarioLayout = new javax.swing.GroupLayout(pnlInfoUsuario);
        pnlInfoUsuario.setLayout(pnlInfoUsuarioLayout);
        pnlInfoUsuarioLayout.setHorizontalGroup(
            pnlInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 330, Short.MAX_VALUE)
                    .addGroup(pnlInfoUsuarioLayout.createSequentialGroup()
                        .addGroup(pnlInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                            .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(pnlInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtNombre, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(pnlInfoUsuarioLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(pnlInfoUsuarioLayout.createSequentialGroup()
                        .addComponent(btnSalir)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnRegistro)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnVer)))
                .addContainerGap())
        );
        pnlInfoUsuarioLayout.setVerticalGroup(
            pnlInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlInfoUsuarioLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnlInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtId, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(17, 17, 17)
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addGroup(pnlInfoUsuarioLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnRegistro)
                    .addComponent(btnVer)
                    .addComponent(btnSalir))
                .addContainerGap(13, Short.MAX_VALUE))
        );

        pnlCartas.add(pnlInfoUsuario, "InicioUsuario");

        pnlTarea.setLayout(new java.awt.BorderLayout());

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel3.setText("Tarea");
        pnlTarea.add(jLabel3, java.awt.BorderLayout.PAGE_START);

        jLabel5.setText("Tarea:");

        jLabel8.setText("Descripcion:");

        jLabel10.setText("Estado:");

        btnParar.setText("Parar");
        btnParar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPararActionPerformed(evt);
            }
        });

        btnSuspender.setText("Suspender");
        btnSuspender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSuspenderActionPerformed(evt);
            }
        });

        jLabel6.setText("Realizado:");

        txtRealizadoTarea.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRealizadoTareaActionPerformed(evt);
            }
        });

        btnGrEstado.add(rbtnPendiente);
        rbtnPendiente.setText("Pendiente");
        rbtnPendiente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnPendienteActionPerformed(evt);
            }
        });

        btnGrEstado.add(rbtnFinalizado);
        rbtnFinalizado.setText("Finalizado");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel5)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTarea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtDescripcion, javax.swing.GroupLayout.DEFAULT_SIZE, 266, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnSuspender)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(btnParar))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addComponent(jLabel10))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(rbtnPendiente)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(rbtnFinalizado)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtEstado, javax.swing.GroupLayout.DEFAULT_SIZE, 130, Short.MAX_VALUE))
                            .addComponent(txtRealizadoTarea))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel5, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtTarea, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jLabel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(txtDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel10, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtEstado, javax.swing.GroupLayout.PREFERRED_SIZE, 14, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(rbtnPendiente)
                        .addComponent(rbtnFinalizado)))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(txtRealizadoTarea, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 98, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnParar)
                    .addComponent(btnSuspender))
                .addContainerGap())
        );

        pnlTarea.add(jPanel1, java.awt.BorderLayout.CENTER);

        pnlCartas.add(pnlTarea, "Tarea");

        pnlSuspender.setLayout(new java.awt.BorderLayout());

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Suspender");
        pnlSuspender.add(jLabel7, java.awt.BorderLayout.PAGE_START);

        jLabel9.setText("Descripcion:");

        txtDescripcionSuspension.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDescripcionSuspensionActionPerformed(evt);
            }
        });

        btnFinalizarSuspension.setText("Finalizar");
        btnFinalizarSuspension.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarSuspensionActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtDescripcionSuspension, javax.swing.GroupLayout.DEFAULT_SIZE, 262, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnFinalizarSuspension)))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txtDescripcionSuspension, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 189, Short.MAX_VALUE)
                .addComponent(btnFinalizarSuspension)
                .addContainerGap())
        );

        pnlSuspender.add(jPanel2, java.awt.BorderLayout.CENTER);

        pnlCartas.add(pnlSuspender, "Suspension");

        jSplitPane1.setRightComponent(pnlCartas);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 380, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jSplitPane1)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtRealizadoTareaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRealizadoTareaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRealizadoTareaActionPerformed

    private void rbtnPendienteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnPendienteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rbtnPendienteActionPerformed

    private void listProyectosMouseReleased(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_listProyectosMouseReleased
        // TODO add your handling code here:
        if(evt.getClickCount() >= 2){
            proyecto = EmpresaControlador.getInstance().getProyecto(listProyectos.getSelectedIndex());
            List<Tarea> tareas = proyecto.getTareas();
            cargarListaTareas(tareas);
        }
    }//GEN-LAST:event_listProyectosMouseReleased

    private void btnSalirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSalirActionPerformed
        visitador.cambiarTarjeta("Inicio");
    }//GEN-LAST:event_btnSalirActionPerformed

    private void btnVerActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVerActionPerformed
        // TODO add your handling code here:
        cambiarTarjeta("Tarea");
        tarea = proyecto.getTareas().get(listTareas.getSelectedIndex());
        llenarCamposTarea(tarea);
        registroTrabajo = new RegistroTrabajo(new DateTime(), usuario, tarea);
        EmpresaControlador.getInstance().agregarRTrabajo(registroTrabajo);
    }//GEN-LAST:event_btnVerActionPerformed

    private void txtDescripcionSuspensionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDescripcionSuspensionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDescripcionSuspensionActionPerformed

    private void btnFinalizarSuspensionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarSuspensionActionPerformed
        cerrarRSuspension();
        cambiarTarjeta("InicioUsuario");
    }//GEN-LAST:event_btnFinalizarSuspensionActionPerformed

    private void btnSuspenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSuspenderActionPerformed
        cerrarRTarea();
        cambiarTarjeta("Suspension");
        registroSuspension = new RegistroSuspension(new DateTime(), usuario);
        EmpresaControlador.getInstance().agregarRSuspension(registroSuspension);
    }//GEN-LAST:event_btnSuspenderActionPerformed

    private void btnPararActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPararActionPerformed
        cerrarRTarea();
        cambiarTarjeta("InicioUsuario");
    }//GEN-LAST:event_btnPararActionPerformed

    public void setVisitador(TrabajadorVisitador visitador) {
        this.visitador = visitador;
    }
    
    public void setUsuario(Usuario usuario){
        this.usuario = usuario;
    }
    public void iniciarFormulario(Usuario usuario){
        setUsuario(usuario);
        llenarCamposUsuario();
        cargarListaProyectos();
    }
    public void llenarCamposUsuario(){
        txtNombre.setText(usuario.getNombre());
        txtId.setText(Long.toString(usuario.getId()));
    }
    public void llenarCamposTarea(Tarea tarea){
        txtTarea.setText(""+ tarea.getNombre());
        txtDescripcion.setText(""+ tarea.getDescripcion());
        if(tarea.isEstado())
            rbtnFinalizado.setSelected(true);
        else
            rbtnPendiente.setSelected(true);
    }
    public void cargarListaProyectos(){
        
        proyectos = usuario.getProyectos();
        modeloListaP = new DefaultListModel();
        for (int i = 0; i < proyectos.size(); i++) {
            modeloListaP.addElement(proyectos.get(i).getNombre());
        }
        listProyectos.setModel(modeloListaP);
    }
    
    public void cargarListaTareas(List<Tarea> tareas){
        modeloListaT = new DefaultListModel();
        for (int i = 0; i < tareas.size(); i++) {
           modeloListaT.addElement(tareas.get(i).getNombre());
        }
        listTareas.setModel(modeloListaT);
    }    
    public void vaciarCamposSuspension(){
        txtDescripcionSuspension.setText("");
    }
    public void cambiarTarjeta(String tarjeta){
        ((CardLayout) pnlCartas.getLayout()).show(pnlCartas, tarjeta);
        switch (tarjeta) {
            case "Tarea":
                vaciarCamposTarea();
                break;
            case "Suspension":
                vaciarCamposSuspension();
                break;
        }
    }
    public void vaciarCamposTarea(){
        txtRealizadoTarea.setText("");
    }
    public void cerrarRTarea(){
        tarea.setEstado(rbtnFinalizado.isSelected());
        registroTrabajo.setFin(new DateTime());
        registroTrabajo.setContador(difTime(registroTrabajo.getInicio(), registroTrabajo.getFin()));
        System.out.println(""+ registroTrabajo.getContador().getMinutes());
        registroTrabajo.setDescripcion(txtRealizadoTarea.getText());
    }
    public void cerrarRSuspension(){
        registroSuspension.setFin(new DateTime());
        registroSuspension.setTipoSuspesion(txtDescripcionSuspension.getText());
        registroSuspension.setContador(difTime(registroSuspension.getInicio(), registroSuspension.getFin()));
    }
    public Minutes difTime(DateTime inicio, DateTime fin){
        return Minutes.minutesBetween(inicio, fin);
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizarSuspension;
    private javax.swing.ButtonGroup btnGrEstado;
    private javax.swing.JButton btnParar;
    private javax.swing.JButton btnRegistro;
    private javax.swing.JButton btnSalir;
    private javax.swing.JButton btnSuspender;
    private javax.swing.JButton btnVer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JList listProyectos;
    private javax.swing.JList listTareas;
    private javax.swing.JPanel pnlCartas;
    private javax.swing.JPanel pnlInfoUsuario;
    private javax.swing.JPanel pnlSuspender;
    private javax.swing.JPanel pnlTarea;
    private javax.swing.JRadioButton rbtnFinalizado;
    private javax.swing.JRadioButton rbtnPendiente;
    private javax.swing.JLabel txtDescripcion;
    private javax.swing.JTextField txtDescripcionSuspension;
    private javax.swing.JLabel txtEstado;
    private javax.swing.JLabel txtId;
    private javax.swing.JLabel txtNombre;
    private javax.swing.JTextField txtRealizadoTarea;
    private javax.swing.JLabel txtTarea;
    // End of variables declaration//GEN-END:variables
    private TrabajadorVisitador visitador;
    private DefaultListModel modeloListaP;
    private List<Proyecto> proyectos;
    private Proyecto proyecto;
    private Usuario usuario;
    private Tarea tarea; 
    private RegistroTrabajo registroTrabajo;
    private RegistroSuspension registroSuspension;
    private DefaultListModel modeloListaT;
}
